### ISSUE TITLE
I just wanted to ask about history of Monocast burning/life

### ISSUE THREAD

**Issue by mediaexplorer74** [adderthorn/Monocast#2]
Hello Noah,

I just wanted to ask about history of Monocast burning/life.

Today I forked your [Monocast](https://github.com/adderthorn/Monocast) and discovered .netstandard 1.3 "link", and "Mobile" deals ;)
Did you have some Windows 10 Mobile device at last time? =)   
I tried to downgrade main Monocast module (UWP) to SDK 15063.  The result: app can start, but shows "blank screen". 
I checked adaptive triggers (XAML)... and decreased minwidth values... Result: epic fail :) 

Best,
Andrey aka MediaExplorer

**Comment by adderthorn** [comment]
Hello Andrey,

When I originally wrote Monocast, the primary goal was a mobile-first client. I did own and use a Lumia 950 XL at the time. As Windows 10 mobile was discontinued, I focused Monocast for the desktop and XBox.

It's been a long time since I've tried targeting such an old version of the UWP SDK, so I'm not sure if it will work, especially after adapting the WinUI2 controls.

Cheers,
Noah

**Comment by mediaexplorer74** [comment]
Noah, 

Thank you very much for your answer(ing) :) After exploring the code I want to say only 2 (3) words: you are cool C# developer. I have no even 10 % of your skills .. So I stopped Monocast RnD =) I assembled another (simplest, 1-podcast) Radio-T-UWP app for my own minimal travelling needs (only "background" listening one Radio-T show of last IT geeks, and Russian relocators to America, via my old sweet Lumia 950). 

Have a nice time (day or night) ,
Andrey

**Comment by adderthorn** [comment]
Hello Andrey,

Thank-you for the kind words. I do plan on adding some enhancements to Monocast in time now that WinUI3 is mostly final. Good luck with your programming!

Noah
